services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/project/build:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: always
    networks:
      - frontend_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/project:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - frontend_network

  attacker:
    build:
      context: ./attacker_webserver
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/data:/var/lib/postgresql/data
    restart: always

  waf:
    build:
      context: ./waf_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./waf_server/project:/src
    command: sh -c "gcc -O2 /src/waf.c -levent -lpcre2-8 -o /src/waf && /src/waf"
    depends_on:
      - nginx
    restart: always
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge